### ISSUE TITLE
Vipps subscription integration

### ISSUE THREAD

**Issue by CootieMonster** [vippsas/vipps-developers#107]
Hello Vipps team, is there any online documentation for integrating Vipps for automatic recurring monthly payments?

**Comment by cloveras** [comment]
Hello! 

It is "automatic": https://github.com/vippsas/vipps-developers/blob/master/newsletters/2022-01-newsletter.md#recurring-api-the-processing-status

More: https://github.com/vippsas/vipps-recurring-api

**Comment by cloveras** [comment]
Have you not seen https://github.com/vippsas/vipps-developers?

**Comment by CootieMonster** [comment]
I think those are the links I've needed. Excuse my laziness.

Thank you. 

I'm closing the issue.
