### ISSUE TITLE
String error in BankID app 1.6.0

### ISSUE THREAD

**Issue by subhappy** [vippsas/vipps-developers#108]
Should be "Nordea Direct", was "%1$s".
As a customer this makes me nervous about the application.
However it works after closing and restarting the app. 
![Screenshot_20220123-201413](https://user-images.githubusercontent.com/10207175/150694786-595a8ecc-6903-4f3a-a760-c186f3a32570.jpg)

**Comment by flinkgutt** [comment]
Thank you for this report 😃  
It's been identified and fixed, it will be part of the next release of the app :)
