### ISSUE TITLE
Build of Vipps MT (iOS) is removed from TestFlight.

### ISSUE THREAD

**Issue by artem-stupko-axon** [vippsas/vipps-developers#116]
There is no possibility to use Vipps MT on iOS devices.
The last build is removed/expired from TestFlight.
Could you please download a new build to TestFlight or give some advice on how to test integration with Vipps on the test environment, please?
![image](https://user-images.githubusercontent.com/44087046/154510237-05df80ef-2bf0-450d-b755-2bfc172fb5ef.png)

**Comment by cloveras** [comment]
Hi

Yes, it’s expired, sorry. A new version has been sent to Apple, and should be available soon. 

Christian, Vipps

**Comment by artem-stupko-axon** [comment]
Thanks a lot!

**Comment by flinkgutt** [comment]
@artem-stupko-axon A new version is available now. :)

**Comment by artem-stupko-axon** [comment]
It works!
Thanks.
