### ISSUE TITLE
issue with callback

### ISSUE THREAD

**Issue by DaniyalCuboid19** [vippsas/vipps-developers#133]
After 08/04/2022 our server is not receving response on callback url for most of transactions.

**Comment by DaniyalCuboid19** [comment]
Order is not registered in our backend due missing callback response but in vipps dashboard it's showing reserved. 

When i see API dashboard here i can also pointout that callback is missing in this section.

![Screenshot 2022-04-13 at 09 03 34](https://user-images.githubusercontent.com/43741277/163119375-4d6e858b-6956-4002-9596-5352c65b9f14.png)

**Comment by DaniyalCuboid19** [comment]
Order / Payment was reserved on 2022-04-13 07:55:59 and callback is received 2022-04-13T05:56:05.651Z with orderId 
1649829359899

Our server received all the callback now and change the status of payments.

**Comment by cloveras** [comment]
Callbacks are not sent for all statuses. See https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#callbacks

In the same section: "Please note: Do not rely only on callbacks alone, but also poll the /details endpoint as described in [Polling guidelines](https://github.com/vippsas/vipps-developers/issues/133#polling-guidelines)."

See also the checklist: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-checklist.md

"The Merchant must not rely on fallback or callback alone, and must poll [GET:/ecomm/v2/payments/{orderId}/details](https://vippsas.github.io/vipps-ecom-api/#/Vipps%20eCom%20API/getPaymentDetailsUsingGET) as documented (this is part of the first item in this checklist, but it's still a common error)."
