### ISSUE TITLE
Payment request not appearing in Vipps MT

### ISSUE THREAD

**Issue by geekus** [vippsas/vipps-developers#142]
Hi,

I'm experiencing issues with making payments in the Vipps MT app. Initiated from web on different device, through Adyen drop in component. I've tried pull to reload in the payments tab several times, also logged out and back in, removing profile from phone, in addition to uninstalled app and reinstalled. 

After a while they end up as expired in the payment history, so they are registered with the phone number at some point. The successful ones in the list in the attached screenshot are when initiating the payment from the same phone as the app is installed on.

Is there any way to debug this? I've tested several phone numbers that work for others in my team.

<img width="300" src="https://user-images.githubusercontent.com/6450570/167894019-0141f42e-1b69-4a23-bf2c-267a74c87ab5.png"> <img width="210" src="https://user-images.githubusercontent.com/6450570/167894112-f1a6b687-7cb0-4869-a109-15e31a9f3289.PNG"> <img width="210" src="https://user-images.githubusercontent.com/6450570/167894572-17bb471d-b2fc-4689-ba87-9414c2383393.PNG">

**Comment by cloveras** [comment]
Hi! Can you please try the app without an emulator? As the documentation for the test environment says, emulators may not be 100 % like the «real» app.

**Comment by geekus** [comment]
The Vipps MT app is on my iPhone. What might look like an emulator is Firefox in responsive mode, the browser where I'm initiating the payment request.

**Comment by geekus** [comment]
With the latest update 4.47.0 (430) that just popped up in TestFlight it now works again. 👍 Closing issue.
