### ISSUE TITLE
Test phone number works for payments API but not login

### ISSUE THREAD

**Issue by pdewouters** [vippsas/vipps-developers#143]
Hi

When I submit the phone number on the login screen, it shows the error "To log in with Vipps you need to have Vipps on your phone and be at least 15 years old." , the POST request is sent to `https://api.vipps.no/vipps-login-idp/fetch-api/login`

In the FAQ, it says that error happens if using a real user in the test environment, but that isn't the case, and it works with payments.

Any idea how to fix this issue?

Thanks

**Comment by cloveras** [comment]
Btw: If you have any additional info, that can help. See: https://github.com/vippsas/vipps-developers/blob/master/contact.md#what-to-include-in-the-email

**Comment by cloveras** [comment]
Hi again

You say that you are using the test environment, but it looks like you are using api.vipps.no, which is the production environment.

Are you sure you are not mixing the users and environments?

**Comment by pdewouters** [comment]
Thanks - I've had help from the Vipps support, works great now!
