### ISSUE TITLE
Please change the language on the demo.vipps.no to english

### ISSUE THREAD

**Issue by terchris** [vippsas/vipps-developers#144]
Hi
I look at the demo.vipps.no and see that what I want is the simple "Vipps Hurtigkasse". 
The language of the github doc is in english - so I need to read the whole doc to figure out the english term for "Vipps Hurtigkasse".

Suggest you translate the demo.vipps.no to english or add the english term for "Vipps Hurtigkasse" 

Regards
Terje

**Comment by cloveras** [comment]
Hi! 

Vipps is only available for Norwegian users, and merchants that accept Vipps must have a Norwegian presence - see https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md#foreign-companies

Almost all users of demo.vipps.no are Norwegian, but internationalization is of course our ambition. 

In the meantime: Can you use Google Chrome with automatic translation?
