### ISSUE TITLE
Vipps b

### ISSUE THREAD

**Issue by funkitptent** [vippsas/vipps-developers#149]
@funkitptent

**Comment by cloveras** [comment]
Hello! Is there something we can help with?

**Comment by Carlmartinsen** [comment]
Hello. We have installed Vipps in Klarna Checkout and as Vipps Express. Both work as far as orders coming into woocommerce but the express version stops in woocommerce and is not uploaded automtically to "ASW". 
<img width="310" alt="Skjermbilde 2022-06-27 kl  14 19 12" src="https://user-images.githubusercontent.com/108277880/175944941-dec687ca-1101-4747-82ff-2dbf8b8c26cf.png">
<img width="298" alt="Skjermbilde 2022-06-27 kl  14 19 40" src="https://user-images.githubusercontent.com/108277880/175944947-90bfa962-6bca-4fe0-b6f1-58bcda7c9df9.png">

**Comment by cloveras** [comment]
Hi @Carlmartinsen 

This looks like WooCommerce. If that's correct, please use the support forum here: https://wordpress.org/support/plugin/vipps-recurring-payments-gateway-for-woocommerce/

See also: https://github.com/vippsas/vipps-developers/blob/master/contact.md
