### ISSUE TITLE
AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application'

### ISSUE THREAD

**Issue by xXAvoraXx** [vippsas/vipps-developers#153]
I got this error "AADSTS9002326" when I request to apitest.vipps.no.

You need to look at the solution for this error.
[Solution](https://github.com/Intility/fastapi-azure-auth/issues/47)

I've been dealing with this issue for weeks now, by setting up a proxy on my own server, I've forwarded the requests and solved the cross-origin issue. The error I get can be fixed by you.

https://stackoverflow.com/questions/72575793/aadsts9002326-cross-origin-token-redemption-is-permitted-only-for-the-single-p

**Comment by xXAvoraXx** [comment]
I could'nt solve this issue

**Comment by cloveras** [comment]
Hi @xXAvoraXx 

Sorry for the late reply.

CORS is documented in our FAQ: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#why-do-i-get-a-cors-error

----

Why do I get a CORS error?

If you get a CORS (Cross-Origin Resource Sharing) error, it is from your side, not an error from Vipps. You are most likely attempting to call the Vipps API from a website, and your webserver's configuration prevents it.

CORS is a protocol that enables scripts running on a browser client to interact with resources from a different origin. Sometimes servers are configured to prevent this, and that results in a CORS error.

Vipps only receives the API requests over HTTPS, and has no way of detecting how the request was made on the caller side - it all looks the same. We can not fix the CORS error for you.

You can read more about CORS here: [CORS Tutorial: A Guide to Cross-Origin Resource Sharing](https://auth0.com/blog/cors-tutorial-a-guide-to-cross-origin-resource-sharing/).
