### ISSUE TITLE
Test app not getting open with deeplink on Android 12 and 13

### ISSUE THREAD

**Issue by mddanishansari** [vippsas/vipps-developers#156]
Deeplink opens the app perfectly fine on all devices before Android 12 but in Android 12 and 13 it opens the default browser.

Deeplink is in this format
https://apitest.vipps.no/dwo-api-application/v1/deeplink/vippsgateway?v=2&token=TOKEN_GOES_HERE

And my code is as follows
```kotlin
// This intent opens app in Android 11, 10, 9 etc but opens browser in Android 12 and 13
val intent = Intent(Intent.ACTION_VIEW).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        data = Uri.parse(deepLink)
}
startActivity(intent)
```

And my guess is that it's due to web intent resolution changes in Android 12
https://developer.android.com/about/versions/12/behavior-changes-all#web-intent-resolution

Let me know if you need more details and if I'm missing something

**Comment by cloveras** [comment]
Hi @mddanishansari 

Sorry for the very late reply. 

I have asked the app team for input.

Are you developing a native app? Can you give us some more details? See https://github.com/vippsas/vipps-developers/blob/master/contact.md for tips.

**Comment by hanspeide** [comment]
You're right, @mddanishansari. It looks like there are both missing and incorrect SHA's used in our assetlinks.json files for the MT app. We will are looking into this.

You should have received an app picker when triggering the deeplink. If that is not the case, can it be that you've previously set this to always open the browser when triggering the deeplink? 
![image](https://user-images.githubusercontent.com/325118/187410689-302593a5-0d93-46c6-be4d-cf038ed8b252.png)

A workaround is to either clear which app is opened by default, or to open the system settings for the Vipps MT app, open "Open by default", click "Add Link" and then tick all the checkboxes.

**Comment by hanspeide** [comment]
@mddanishansari We've deployed new assetlinks.json files, so this should now be fixed
