### ISSUE TITLE
Vipps express checkout returns error message "kunne ikke sette leveringsadresse"

### ISSUE THREAD

**Issue by voksnevad** [vippsas/vipps-developers#169]
Vipps hurtigkasse stopped working on our site sunday 11.09.22.

Using WooCommerce and Vipps for WooCommerce integration on [https://www.lundqvist-hundeskole.no/butikk/](url)

When customers choose "Vipps hurtigkasse", Vipps returns the errormessage "kunne ikke sette leveringsadresse".

Allways worked fine, this problem occured sunday 11.09.22.

![305690490_1246493122841547_7570096384928413451_n](https://user-images.githubusercontent.com/113424825/189856184-2e2db6f4-03e2-498e-9ed0-de9fc86e157b.jpg)

**Comment by matsjohans** [comment]
Hei, kan du sende oss en epost på integration@vipps.no. Vi ser noen feil når vi returnerer callback som kan påvirke dette. 
Mvh Mats
/Vipps
