### ISSUE TITLE
død lenke "Documentation for webhooks" i login setup på portal.vipps.no

### ISSUE THREAD

**Issue by peterbb** [vippsas/vipps-developers#175]
I forbindelse med oppsett av "vipps login" på portal.vipps.no så vises følgende skjermbilde, med lenken "Documentation for webhooks" som peker til `https://github.com/vippsas/vipps-login-api/blob/master/vipps-login-webhooks.md` . Det er en død lenke. Filen ble fjernet i denne commit-en https://github.com/vippsas/vipps-login-api/commit/3e887d0ce94cc4650f5dc19d1302279c1455679f.

![image](https://user-images.githubusercontent.com/789911/190706187-b80a2355-b4eb-4f59-8ba1-0d2a82df710c.png)

**Comment by cloveras** [comment]
Hi! thanks formulering us know, and sorry for the super slow response. @thormarius is on it.
