### ISSUE TITLE
Send money button/deeplink

### ISSUE THREAD

**Issue by noeltock** [vippsas/vipps-developers#249]
Hi there, apologies if this is the wrong place.

I'm trying to create a simple website deep link/donate button to open the app and show the amount screen. What is the best way to go about this?

Thank you in advance 🙏🏻

**Comment by cloveras** [comment]
Hello, and sorry for the super late response

I suspect you found a solution, but in case not: Sounds like you need the eCom or ePayment API. See: https://vippsas.github.io/vipps-developer-docs/

**Comment by cloveras** [comment]
Closing now, and also mentioning the new link: https://developer.vippsmobilepay.com
