### ISSUE TITLE
Hyvä combat module

### ISSUE THREAD

**Issue by thaulow** [vippsas/vipps-developers#271]
Hello, 

Have Vipps considered making a combat module for supporting Hyvä? Would be nice for us migrating from Luma to Hyvä, as I am guessing it will be quite many of us in the future, that do not want to go down the PWA Studio road :) 

https://gitlab.hyva.io/hyva-public/module-tracker/-/boards

**Comment by cloveras** [comment]
No plans for that, sorry. See https://developer.vippsmobilepay.com/docs/vipps-plugins
