### ISSUE TITLE
vipps MT expired credit card.

### ISSUE THREAD

**Issue by DaniyalCuboid19** [vippsas/vipps-developers#286]
Credit card is expired in vipps MT ios. 

last time we used this link to activate this. 

https://github.com/vippsas/vipps-developers/tree/master/testdata#credit-card-numbers

But now this link is not working.

**Comment by cloveras** [comment]
Please contact us to get a new test user: https://developer.vippsmobilepay.com/docs/vipps-developers/test-environment#test-users
