### ISSUE TITLE
I want to test my integrations

### ISSUE THREAD

**Issue by AKCT1** [vippsas/vipps-developers#308]
Hello Team, 
Can anyone help me how can i test my vipps integration, i am from india and my norway client need to setup this and for which i have to create account in vipps. So can any one guide me how can i create accoutn in vipps from india. And get the credentials to test and build vipps integration with current application. 
Hopw you guys got the issue. 
Please help me out i am getting too much down now
Thanks,

**Comment by cloveras** [comment]
Hi! Please see https://developer.vippsmobilepay.com/docs/vipps-developers/test-environment and search the documentation.
