### ISSUE TITLE
When is "cancel payment" needed?

### ISSUE THREAD

**Issue by aanders77** [vippsas/vipps-developers#334]
Hi! We just became a Vipps Partner a few days ago, and we're working on integrating all the endpoints of the ePayment API. One of them is "Cancel payment". 
In order to keep our admin panel intuitive and easy to use, I just want to know in what cases "Cancel payment" should be used? 
Typically, the user will initiate the payment themselves, and we will capture it immediately after they approve it in their app. If they decide to not approve the payment after all, then there will be no user input and thus we will not be aware of it. How can we know that we should cancel the payment, then?

**Comment by cloveras** [comment]
Hello!

Sorry about the very late response. It's normally faster: https://developer.vippsmobilepay.com/docs/vipps-developers/contact/

Cancel may be required if you are not able to deliver what the customer paid for. See: https://developer.vippsmobilepay.com/docs/vipps-developers/common-topics/cancel/
