### ISSUE TITLE
Card payment, return from Bank Id fails

### ISSUE THREAD

**Issue by dag-sunde** [vippsas/vipps-developers#337]
The flow: 
initiate a card payment --> the user fill in card info --> approves in BankID --> BankId returns to Vipps.

This works flawlessly here in Norway.

When my App developers in CapeTown, SA are testing with their South African Visa or Mastercards, the flow fails with a 404 returned to the SA bankId providers. So it never return to Vipps with the Approval.

These are the different BankId providers in question:

- https://acsabsa.bankserv.co.za/
- https://3ds2.standardbank.co.za/web/
- https://assets.standardbank.co.za/

And this is the URL they are trying to call:

> [https://pe.vipps.no/payments/v1/web/fscp-verification-callback?verificationToken=NgV3ZAAAAABvdD1UWXdaVmdB]...]

Is there any Black/Whitelist that Vipps operates, that denies South African credit cards to use this part of Cipps Payments?

**Comment by dag-sunde** [comment]
Maybe this will be more clear:

1. Browser sends a GET to /payments/v1/web/fscp-verification-callback from https://checkoutshopper-live.adyen.com/.
2. Browser gets a 303 redirect to : https://cards.vipps.no/checkout/auth
3. Browser tries to navigate to redirect URL
4. Gets a 404.

**Comment by cloveras** [comment]
Hello! 

Sorry about the very late response. It's normally faster: https://developer.vippsmobilepay.com/docs/vipps-developers/contact/

There have been some improvements on FSCP, so hopefully you get an understandable error message now..?

See also: https://developer.vippsmobilepay.com/docs/vipps-developers/faqs/users-and-payments-faq/#card-payments
