### ISSUE TITLE
Unable to get Callback after success payment in iOS 

### ISSUE THREAD

**Issue by Shubhamkavyasoftech** [vippsas/vipps-developers#37]
Hello support team,
we are integrating the vipps for ios but we are unable to get a callback from vipps to my app.
can you plz let me know what should we do.
thanx!

**Comment by flinkgutt** [comment]
Hi

We are going to need some more details regarding your request and what APIs you are trying to use.
Also this is a question best suited to be raised by sending an e-mail to integration@vipps.no, as described on https://github.com/vippsas/vipps-developers/blob/master/contact.md

Please pay particular attention to the https://github.com/vippsas/vipps-developers/blob/master/contact.md#what-to-include-in-the-email

Regards
Christian Michelsen
APIs & Integration
