### ISSUE TITLE
[Android app] Bug when payment in process

### ISSUE THREAD

**Issue by Tynx11** [vippsas/vipps-developers#39]
When I first start paying everything is ok. But as soon as I close the VIPPS android view, and start the payment process again with the same token, the Android VIPPS application displays a empty white screen without any error. On the IOS, under the same scenario, showing the error message "Payment already started". Implements android vipps app like this
![image](https://user-images.githubusercontent.com/22071044/72161564-67bf6780-33d1-11ea-9690-75de2fb18a87.png)

an error occurs on all versions of the application

**Comment by cloveras** [comment]
Hi

Thanks for reporting this, and sorry for the late response. I will notify the Android team.

Christian, Vipps

**Comment by cloveras** [comment]
Btw: We are normally quicker to respond - see: https://github.com/vippsas/vipps-developers/blob/master/contact.md

**Comment by thomanil** [comment]
@Tynx11 Fix for this is merged. The Android version will behave the same as iOS for these cases (show "payment already started" message in the app) starting with v2.16 of the Android app (most likely releasing next week to users and MT test environment).
