### ISSUE TITLE
Can't install Android test app via provided link. 

### ISSUE THREAD

**Issue by kentrh** [vippsas/vipps-developers#41]
The page that is supposed to link to an Android test version only states: 

> No releases for this app. You’ll receive an email once this app is released.

https://install.appcenter.ms/orgs/vipps/apps/vipps-android/distribution_groups/mt testers

**Comment by sindrenm** [comment]
Hi, @kentrh! Thanks for reaching out. Just to be sure that this isn't an issue with handling the space in the URL, could you try with the link below?

https://install.appcenter.ms/orgs/vipps/apps/vipps-android/distribution_groups/mt%20testers

Let me know if that still doesn't doesn't work. :slightly_smiling_face:

**Comment by cloveras** [comment]
Hi @kentrh 

I am not sure if I understand the problem.

The link to "App Cdenter" on https://github.com/vippsas/vipps-developers#android is "https://install.appcenter.ms/orgs/vipps/apps/vipps-android/distribution_groups/mt%20testers", with "%20" and not " ".

Christian, Vipps

**Comment by kentrh** [comment]
Hi, again and thanks for your reply. Looks like it's working with %20, and I'm quite positive I swapped the space for %20, but then again, it was saturday evening, so I can't be sure. Anyway, thanks for your help, and sorry for my noobness. 

Anywho, could you please update the App Center url here https://github.com/vippsas/vipps-developers#android with %20 instead of space? 

Cheers.

**Comment by cloveras** [comment]
Hi @kentrh 

The URL has always had "%20", as you can see in the source and the history: https://github.com/vippsas/vipps-developers/blame/master/README.md#L183

Christian, Vipps
