### ISSUE TITLE
[Request] Add webhook as a subscribe method to status page

### ISSUE THREAD

**Issue by vikre** [vippsas/vipps-developers#43]
Hi,

I was wondering if it was possible to activate webhook as a subscribe method on the status page (ref: https://help.statuspage.io/help/email-and-sms-notifications )?

**Comment by cloveras** [comment]
Hi @vikre 

It's done 🎉

Christian, Vipps

**Comment by vikre** [comment]
Thanks! 🤩

**Comment by cloveras** [comment]
Hello again

It seems we may need some additional regulatory approval for this, so I have to disable it again, until we have received confirmation/approval.

Sorry.

Christian, Vipps.
