### ISSUE TITLE
Golang client library for Vipps Ecom/Recurring

### ISSUE THREAD

**Issue by torfjor** [vippsas/vipps-developers#44]
Hi Vipps! 👋

First of all, thanks for an awesome product with great documentation! Integrating with you guys have been a breeze. 🎉 

Just thought I'd let you know that I open sourced a library for interacting with EcomV2 and Recurring Payments in Go: [go-vipps](https://github.com/torfjor/go-vipps). It's still in the early stages of development, but should be quite feature complete.

**Comment by cloveras** [comment]
Hi @torfjor 

Nice! And thanks for the kind words!

We really like to see others using the Vipps APIs, and if you have any questions, improvements, etc: Please let us know. Use the "issues", submit a PR, or contact us directly: https://github.com/vippsas/vipps-developers/blob/master/contact.md

Christian, Vipps

**Comment by cloveras** [comment]
Btw: We are working on an additional way of documenting the APIs, with Slate. You can see a work in progress here, with examples in Go and other languages: https://vpsataccentor.github.io/vipps-ecom-api/build/#vipps-ecommerce-api-vipps-ecom-api

No guarantees! 😅

**Comment by cloveras** [comment]
Hi, @torfjor 

The API documentation is now available in Swagger UI, ReDoc and Shins (similar to Slate) - see https://github.com/vippsas/vipps-recurring-api

Christian, Vipps
