### ISSUE TITLE
Support for custom claims in JWT

### ISSUE THREAD

**Issue by RyszardRzepa** [vippsas/vipps-developers#50]
Hey,

I can´t find this feature in the docs.
Does vipps auth support adding custom claims into JWT  token? 

Example of how firebase  auth  support this feature: https://firebase.google.com/docs/auth/admin/custom-claims#set_and_validate_custom_user_claims_via_the_admin_sdk

example custom claim:

```
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "1234567890",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  }
}
```

**Comment by tht13** [comment]
Hi @RyszardRzepa 
This is not something we have support for in our authentication solution, apologies for this.

Could you expand on your use case for this? It would be nice to get a better understanding so we can consider if this is a feature worth investing time in.

**Comment by cloveras** [comment]
Hi @RyszardRzepa 

Apologies for the hideously late response.

The functionality you describe is not something Vipps will implement, sorry.

Christian, Vipps
