### ISSUE TITLE
Accsess denied

### ISSUE THREAD

**Issue by BPNO** [vippsas/vipps-developers#52]
Hi, developer making new app with Vipps AS payment. We Get the Same response. Access denied due to invalid subscription key. Even if We tried to regenrate the keys. See screenshot 1. 

Screenshot nr 2. It is by using testing IDS which VIPPS provided. Here you can see we get token from them so we can proceed to next step which is sending back token for further payment process.

Can someone plz contact us on e Mail.
adeel2211@gmail.com

**Comment by BPNO** [comment]
No one that have had the same problem with this?

**Comment by tht13** [comment]
Hi @BPNO if the first screenshot is your production keys then it is because you were still using the test url (apitest.vipps.no) production is (api.vipps.no)
also I have deleted the screenshots as they contained your keys in clear text, please regenerate all keys you have immediately.

**Comment by BPNO** [comment]
Thank you,
I will forward this Mail to developer.

We will regenerate. 

Med vennlig hilsen

David Steinmann
Daglig Leder // Partner

M: 0047 900 600 07
E: ds@benchmark.no
W: www.benchmark.no

Benchmark Performance AS
