### ISSUE TITLE
Ingress missing section on newsletter email

### ISSUE THREAD

**Issue by webmaeistro** [vippsas/vipps-developers#60]
![Screenshot_20201007_172537](https://user-images.githubusercontent.com/19165833/95352321-6bc9d880-08c2-11eb-9c18-83b72781a10a.jpg)

read that sentance it's missing the main 'what' of the entire sentence. If i hadn't lookd it up on github i wouldn't have the faintest ide what actually is beeing announced.

**Comment by cloveras** [comment]
Hi @webmaeistro 

Thanks for the tip! We did notice this right after the newsletter was sent, and I have posted in our internal fuckup channel:

"I deleted that rather crucial part of the sentence in an attempt at reducing the number of links, and simplifying the message. But I deleted the linked text too, not just the link."

We have fixed GitHub, see https://github.com/vippsas/vipps-developers/commit/8f41a9bacf2b6e8a0fdfe1ced6ee6f1c85b812c1, but the sent emails are unfixable.

Christian, Vipps
