### ISSUE TITLE
Vipps for MacOS / Windows / Linux - Desktop app

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-developers#62]
Hi,

Just a question that did came up.

Do you have any plans for a desktop app?
Like telegram or whatsapp does.

**Comment by flinkgutt** [comment]
No, we have no plans for a desktop application at this time. 
Unless someone has been hiding their plans in a deep dark hole somewhere and is working on it only in the light from a full moon.

Would be cool though :-)

**Comment by steffanhalv** [comment]
Yes, I don't find any reason why it should not be any. Most of the bills is payed on a computer and if we could use vipps instead of the websites provided by banks it would be allot simpler.

And it is really not that hard to build a desktop app this days with engines like Electron etc.

**Comment by flinkgutt** [comment]
While it's not difficult to create a desktop application, we do need to continue to support it and keep it secure. 
That entails using resources that we, so far at least, consider best spent elsewhere. :-)

And while I personally I find the use of JavaFX way better than Electron, I'll refrain from gathering pitchforks and torches.

But thank you for the suggestion.

**Comment by cloveras** [comment]
Hi @steffanhalv 

I'm closing this, as we have no plans to make apps for macOS, Windows or Linux.

Christian, Vipps
