### ISSUE TITLE
Add support for blesta

### ISSUE THREAD

**Issue by Pomdre** [vippsas/vipps-developers#65]
Add blesta as a plugin.  it's like whmcs
THE BILLING PLATFORM FOR HOSTING PROVIDERS
[Blesta](http://blesta.com)

**Comment by cloveras** [comment]
Hi @Pomdre 

We don’t have that on the roadmap, unfortunately. See the plugin overview here: https://github.com/vippsas/vipps-developers#plugins

All plugins are based on the eCom API, and anyone can make plugins. All our official plugins are open source. 

Christian, Vipps

**Comment by cloveras** [comment]
Hi @Pomdre 

I'm closing this old issue now. See the links above for updated info.

Christian, Vipps
