### ISSUE TITLE
Getting an error responseCode":"1000"

### ISSUE THREAD

**Issue by jmrafiq** [vippsas/vipps-developers#67]
Hi Good afternoon.. 

We are integrating a Vipps e-commerce solution for a client for a Webshop developed in ASP.NET
We are getting the following error, while initiating the payment..

Response Text:
{"responseInfo":{"responseCode":"1000","responseMessage":"Something went wrong. Please try again later."}}

Following is our test URL
https://www.grefsenhudpleie.no/v3/vipps/vippsPayment.aspx

Can you please help and let us know what we are doing wrong..

Thanks in advance.. 

Best Regards
Rafiq Jakate

**Comment by cloveras** [comment]
Hi @jmrafiq 

If this is in our test environment, we have an ongoing incident: https://vipps-test.statuspage.io

Sorry.

Christian, Vipps

**Comment by cloveras** [comment]
If not: https://github.com/vippsas/vipps-developers/blob/master/contact.md

**Comment by jmrafiq** [comment]
Hi Christian, 

Yes, we are using the test environment, however we are doing this from the Web

Will send the details to the integration team.

Thank you for your kind support.. (y)

Best Regards
- Rafiq Jakate

**Comment by cloveras** [comment]
Hi @jmrafiq 

I'll close this (old) issue, then.

Christian, Vipps
