### ISSUE TITLE
Support 0 kr in CampaignRequest

### ISSUE THREAD

**Issue by kmieciu85** [vippsas/vipps-developers#69]
Today in CampaignRequest may only send more then 1 kr, will be nice to support 0 kr also.

```
CampaignRequest{
campaignPrice*	integer($int32)
minimum: 100
example: 1500
The price of the agreement in the discount period. The lowering of the price will be displayed in-app.
end*	string($date-time)
example: OrderedMap {}
The date and time the campaign ends. Needs to be UTC
}
```

**Comment by cloveras** [comment]
Hi @kmieciu85 

Thanks I'll check if there's any new information about this.

Christian, Vipps

**Comment by cloveras** [comment]
Btw: Please try to create issues fdoer the Recurring API in this repository: https://github.com/vippsas/vipps-recurring-api

**Comment by cloveras** [comment]
Hi @kmieciu85 

We don't have any plans to support campaigns with lower amounts than 1 NOK, sorry.

Christian, Vipps

**Comment by kmieciu85** [comment]
Ok., Understand, but I will be fine if it will be possible. 

Sometimes user get for example 1 week or 1 month gratis (0 kr) and after that is billed evry 2 week/month...
In that case we may not display that as a Campaign object, and user don't know when actually we begin to charge him.

Eg, Order without initial charge and may not be promotion since it is gratis/free :)

But if you dont want to support that that is ok. We just need to inform about that our customers, if they ask about it.

Karol

**Comment by mats93** [comment]
Campaigns can be 0kr, OpenAPI documentation has been updated in the [recurring documentation](https://github.com/vippsas/vipps-recurring-api )
