### ISSUE TITLE
Support different Vipps Interval

### ISSUE THREAD

**Issue by kmieciu85** [vippsas/vipps-developers#70]
It shall be possible to support intervals like:
* 15 MONTH, 18 MONTHS, 23 MONTH, 24 MONTH
* 400 DAYS,
* 53WEEKS, 104 WEEKS, 79 WEEKS ...
* 2 YEARS, 3 YEARS  ....
Iven periods looks strange this validation that is today between 1..31 if remember correct is not good enought in some cases...

**Comment by cloveras** [comment]
Hi @kmieciu85 

Is there any type of interval that is impossible to use now? See: https://github.com/vippsas/vipps-recurring-api/blob/master/vipps-recurring-api.md#intervals

Christian, Vipps-

**Comment by kmieciu85** [comment]
There is (was) a limitation on validation, may I send now 18 or 32 month ? or 50 days ?

**Comment by cloveras** [comment]
Hi @kmieciu85 

We have not made any changes to this, and we have to prioritize other tasks. So: No plans to change this for now.

Is this a blocker for you, or can you implement what you need with the current functionality in the API?

Christian, Vipps

**Comment by kmieciu85** [comment]
Hi @cloveras!

It is just some improvements. It works as it is today but our customer are limited to use offers/periods for subscription that Vipps may handle.

Subbestion here are to support other types periods, since this limitation maybe is "to strong"....

**Comment by cloveras** [comment]
Hi @kmieciu85 

Since you are able to do what you need, I will close this issue.

Christian, Vipps

**Comment by kmieciu85** [comment]
We are not able to do what we need/want, we just do what it is possible to do :)
