### ISSUE TITLE
Possibility to "pay once"

### ISSUE THREAD

**Issue by kmieciu85** [vippsas/vipps-developers#71]
Will be fine if vipps recurring API (Faste betalinger) will offer 1 time payment without signing an agreement. 
Sometimes user ned to pay for something onec, it is overkill to draft an agreement or do the integration with "vipps enkeltbetaling"...

May be that possible to do 1 time charge without draft an agreement?  Something like initial charge, but without recurring payment?
Maybe API in "Faste betalinger" that calls eCom api for One time payment without any special integration to that ?

**Comment by tht13** [comment]
This is why we have the Ecom API, please use the Ecom API

**Comment by kmieciu85** [comment]
Ok. Thx for info. I was just wonder if that will be possible when we have allready implemetation of vipps recurring just do a single payment sometimes.... To NOT do whole integration, but if it is not posibble (in the future) then we need to find other solution if we need that :) Thx for info!
