### ISSUE TITLE
Vipps Login - Support Mark icon in login page

### ISSUE THREAD

**Issue by kmieciu85** [vippsas/vipps-developers#72]
Will be fine if Vipps support option to login image in 2 options:
* width login button with whole vipps login (today is supported)
* just icon / mark button to logg in with vipps ()

All other third part ID solution support that: Facebook, Google or Apple....

Sugested solution, is to update https://github.com/vippsas/vipps-design-guidelines that button/mark is also possible to use...

Example (Source picture taken from Apple developer documentation):

![image](https://user-images.githubusercontent.com/20163716/104461717-fbf97700-55af-11eb-85fd-c3aaa0a70050.png)

**Comment by cloveras** [comment]
Hi @kmieciu85 

Thanks for this. I have informed the product owner.

Christian, Vipps

**Comment by VidarHolm** [comment]
Hi Karol! Thank you for your input!

We do offer a logo mark that can be used: https://github.com/vippsas/vipps-design-guidelines/tree/master/vipps-buttons/Vipps%20mark

However it is not recommended to use only the logo mark for Vipps login. Vipps has a strong association to payment and users might not understand that this logo mark gives the option to login (and not do payment).

Please let me know if you have any other input or questions.


Best regards
Vidar, product manager Vipps login

**Comment by kmieciu85** [comment]
Hi!

Yes that is true that you offer logo mark but this is not recommended. Byt may we use vipps logo and vipps mark like that:

Just Logo:

![image](https://user-images.githubusercontent.com/20163716/104471454-2c92de00-55bb-11eb-8665-b5025d1a208a.png)

Whole vipps logo:
![image](https://user-images.githubusercontent.com/20163716/104471055-ad050f00-55ba-11eb-808c-a7c7f2a41316.png)

Will be ok to use logo/mark in both cases even it is not recommended / allowed as it is not written in vipps design guidelines ? https://github.com/vippsas/vipps-design-guidelines

**Comment by VidarHolm** [comment]
Hei Karol. 

Yes you may. Personally I would have chosen a wording more like "Sign up using a third party login" (since neither Vipps nor Apple are social profiles), but that is up to you.

If your buttons are in Norwegian you should use "Log in with Vipps".

Out of the two options you present I would recommend the one in the bottom.

Regards
Vidar

**Comment by kmieciu85** [comment]
Hi! Thanks for reply. Here was just question about grafically representation as a mark icon / long button with text. Thanks for reply that both we may use, in https://github.com/vippsas/vipps-design-guidelines was written that small/mark button like in picture 1 is not allowed... 
Texts english/norwegian or Sign up etc. needs to be configured correctly they are not important just now :) but, thanks for suggestions :)
