### ISSUE TITLE
Test credit cards already in use

### ISSUE THREAD

**Issue by sjelfull** [vippsas/vipps-developers#76]
You note this in testdata/README.md

>Nets offers a series of credit cards with pre-defined characteristics: shop.nets.eu/web/partners/test-cards Response codes: shop.nets.eu/web/partners/response-codes

We can't actually use any of these as they are already in use by someone else, and are required to be unique?

**Comment by cloveras** [comment]
Hi @sjelfull 

Thanks for pointing this out. That part of the documentation is outdated, now that we have changed PSP to Adyen. I updated this now: https://github.com/vippsas/vipps-developers/blob/master/testdata/README.md

Christian, Vipps

**Comment by sjelfull** [comment]
Thanks for that. I'm not sure about ever having received that information. Where can I find it today? And does it allow for testing errors?
