### ISSUE TITLE
"missing subscription key"

### ISSUE THREAD

**Issue by Krisar95** [vippsas/vipps-developers#80]
So I've been trying to get an access token through your test API, and I keep getting 

`"statusCode": 401, "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API."`

What I'm trying to execute is:
```python
# I've obviously hidden the keys, trust that they're there in my file
json_data = '{"client_id" : "xxxxxxx", "client_secret" : "xxxxxxx", "Ocp-Apim-Subscription-Key" : "xxxxxxx" }'

digest = json.loads(json_data)

def get_access_token(mtd, url, data):
    data = json.dumps(data, sort_keys=True, indent=4)
    token = request(mtd, url, params=data)
    return token
    
token = get_access_token("POST", "https://apitest.vipps.no/accesstoken/get", digest)
print(token.content)

```

What am I doing wrong? :thinking:

**Comment by cloveras** [comment]
Hi @Krisar95 

Please see the "C ommon errors" section in the FAQ: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md

And "Quick overview of how to make an API call" in the "Getting started" guide: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md#get-an-access-token

And: The Postman collection to see the correct requests for the eCom API:
- https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-postman.md
- https://github.com/vippsas/vipps-ecom-api

Christian, Vipps

**Comment by cloveras** [comment]
Hi @Krisar95 

I have updated the FAQ: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#why-do-i-get-http-401-unauthorized

Christian, Vipps

**Comment by Krisar95** [comment]
Many thanks Christian
The issue was that I was trying to send my credentials in the request body, not the request headers.
Big oopsie on my part.
