### ISSUE TITLE
Vipps MT account fail

### ISSUE THREAD

**Issue by ArditaMetushi** [vippsas/vipps-developers#86]
Hi,
my test account on vipps mt fail to login and returns 401

**Comment by cloveras** [comment]
Hi @ArditaMetushi 

Maybe there is some useful info in our FAQ: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#why-do-i-get-http-401-unauthorized

Christian, Vipps

**Comment by cloveras** [comment]
You can also see some tips on how to get help quickly here: https://github.com/vippsas/vipps-developers/blob/master/contact.md

**Comment by ArditaMetushi** [comment]
Hi,
its not the api its the vipps test app. i'm tryibg to logib with the test phonenumber and the test pass and i can't

**Comment by ArditaMetushi** [comment]
Hi,
any advise?

**Comment by cloveras** [comment]
Hi @ArditaMetushi 

We need some more details to be able to help. See the links above.

This may also be useful: https://github.com/vippsas/vipps-developers/blob/master/vipps-test-environment.md#vipps-test-apps

Christian, Vipps
