### ISSUE TITLE
(CSV) Settlement report net field not accounting for refund

### ISSUE THREAD

**Issue by fiLLLip** [vippsas/vipps-developers#87]
When reading in settlement reports to Fiken, I discovered that some statements had the wrong value compared to banking transcript. I had to rows with -50,00 in the refund column, and the net column did not consider the refund so the actual payout and net field differed 50,00kr. 

Is it supposed to be like this, or is it a bug? If integrations (like Fiken) need to calculate for it, where is that stated/documented?

**Comment by cloveras** [comment]
Hi @fiLLLip 

Sorry for the late response.

We don't know the Fiken file formats, but all our settlement documentation is here: https://github.com/vippsas/vipps-developers/tree/master/settlements

Christian, Vipps

**Comment by cloveras** [comment]
Closing, since there is no response.
