### ISSUE TITLE
Session destroy

### ISSUE THREAD

**Issue by Digitalmx** [vippsas/vipps-developers#88]
Hi, 
I am using VIPPS payment API for payment. When user used the VIPPS mobile App to pay the amount and cancel the amount.  
It destroy all session I mean if user is logged in after cancelling the payment from mobile App user logged out automatically.
Any idea?

Thanks

**Comment by cloveras** [comment]
Hi @Digitalmx 

Sorry for the late reply.

The Vipps API are REST APIs, and there are no sessions.


Christian, Vipps

**Comment by cloveras** [comment]
Closing, since there is no response.
