### ISSUE TITLE
Vipps express checkout works/doesnt work, seemingly by random

### ISSUE THREAD

**Issue by StianFoll** [vippsas/vipps-developers#99]
Hello! 

I'm having some issues with the plugin "Vipps for woocommerce".

Whenever I try to use the express checkout, it sometimes sends me to the correct place where I would enter my phonenumber, but most of the time I get the error " Vipps er midlertidig utilgjengelig". 

In the logs I get "2021-10-19T11:45:14+00:00 ERROR Kunne ikke opprette Vipps-betaling 500 cURL error 28: Resolving timed out after 5516 milliseconds"

I've tried to disable all the firewalls on the server, but the error still occurs by random. 

If you have any more questions, or need further information, please contanct me at stian@getonnet.no. 

Thank you.

**Comment by iverok** [comment]
This is a DNS issue, probably with api.vipps.no.  It can't be solved in the plugin, but you might try to see what kind of DNS server you are using.

**Comment by cloveras** [comment]
Hi @StianFoll 

If there are problems with the DNS server you are using, you can try to use Google's public DNS server at 8.8.8.8: https://developers.google.com/speed/public-dns

Christian, Vipps
